import React from "react";
import { motion } from "framer-motion";
import { BrainCircuit, Mic, FileDigit, LineChart } from "lucide-react";

const features = [
    {
        name: "AI Mock Interviews",
        description: "Experience dynamic, realistic technical questions that adapt to your performance natively generated by Llama 3.",
        icon: BrainCircuit,
        color: "from-blue-500 to-indigo-500",
    },
    {
        name: "Voice-Based Answers",
        description: "Don't just type. Practice speaking your answers aloud with our real-time voice-to-text integration.",
        icon: Mic,
        color: "from-emerald-400 to-emerald-600",
    },
    {
        name: "Resume-Based Questions",
        description: "Upload your resume and let the AI tailor the interview exactly to your experience and claimed skills.",
        icon: FileDigit,
        color: "from-amber-400 to-orange-500",
    },
    {
        name: "Knowledge Analytics",
        description: "Get granular scoring and actionable feedback highlighting exactly what you need to improve.",
        icon: LineChart,
        color: "from-purple-500 to-pink-500",
    },
];

export function Features() {
    return (
        <section id="features" className="py-24 bg-slate-950 relative overflow-hidden">
            {/* Background decorations */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-indigo-500/5 rounded-full blur-[120px] pointer-events-none" />

            <div className="max-w-7xl mx-auto px-6 lg:px-8 relative z-10">
                <div className="text-center max-w-2xl mx-auto mb-16">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.5 }}
                    >
                        <h2 className="text-indigo-400 font-semibold tracking-wide uppercase text-sm mb-3">
                            Platform Capabilities
                        </h2>
                        <p className="text-3xl sm:text-4xl font-bold tracking-tight text-white mb-4">
                            Everything you need to succeed
                        </p>
                        <p className="text-slate-400 text-lg">
                            Our advanced AI capabilities simulate a rigorous engineering interview to ensure you are ready for the real thing.
                        </p>
                    </motion.div>
                </div>

                <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
                    {features.map((feature, index) => {
                        const Icon = feature.icon;
                        return (
                            <motion.div
                                key={feature.name}
                                initial={{ opacity: 0, y: 20 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                viewport={{ once: true }}
                                transition={{ duration: 0.5, delay: index * 0.1 }}
                                className="group relative"
                            >
                                <div className="h-full bg-slate-900/50 backdrop-blur-md border border-white/5 rounded-2xl p-8 hover:bg-slate-800/50 transition-colors duration-300">
                                    <div className={`mb-6 inline-flex p-3 rounded-lg bg-gradient-to-br ${feature.color} bg-opacity-10 ring-1 ring-white/10 group-hover:scale-110 transition-transform duration-300`}>
                                        <Icon className="w-6 h-6 text-white" />
                                    </div>
                                    <h3 className="text-lg font-semibold text-white mb-3 tracking-snug">
                                        {feature.name}
                                    </h3>
                                    <p className="text-sm text-slate-400 leading-relaxed">
                                        {feature.description}
                                    </p>
                                </div>
                            </motion.div>
                        );
                    })}
                </div>
            </div>
        </section>
    );
}
